# Generated by Django 5.1.2 on 2024-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentwave',
            name='announcementText',
            field=models.TextField(default=None, null=True),
        ),
    ]
