import type { Metadata } from "next";
import "./globals.css";

// React Query
import RQClientProvider from "@/providers/RQClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RQClientProvider>{children}</RQClientProvider>
      </body>
    </html>
  );
}
