import type { Metadata } from "next";
import "./globals.css";

// React Query
import RQClientProvider from "@/providers/RQClientProvider";
import Header from "@/components/headers";

// Next
import { cookies } from "next/headers";

// Constants
import { SESSION_UID_COOKIE_NAME, SESSION_ID_TOKEN_COOKIE_NAME } from "@/constants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const uid = cookies().get(SESSION_UID_COOKIE_NAME)?.value || null;
  const sessionIdToken = cookies().get(SESSION_ID_TOKEN_COOKIE_NAME)?.value || null;

  return (
    <html lang="en">
      <body>
        <RQClientProvider>
          <Header uid={uid} sessionIdToken={sessionIdToken} />
          {children}
        </RQClientProvider>
      </body>
    </html>
  );
}
