# Generated by Django 5.1.1 on 2024-10-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.TextField(null=True, unique=True),
        ),
    ]
