# Generated by Django 5.1.1 on 2024-10-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='category',
        ),
        migrations.AddField(
            model_name='activity',
            name='categories',
            field=models.ManyToManyField(related_name='activities', to='domain.activitycategory'),
        ),
    ]
