# Generated by Django 5.1.1 on 2024-10-12 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_alter_maintenanceticket_maintenancestaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='domain.activity'),
        ),
        migrations.AlterField(
            model_name='file',
            name='maintenanceTicket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='domain.maintenanceticket'),
        ),
    ]
